#ifndef TREE_TYPES__ENUM_H
#define TREE_TYPES__ENUM_H

enum TREE_TYPE__ENUM {
    // TOKEN_TYPE_UNDEF,
    // TOKEN_TYPE_INT,
    // TOKEN_TYPE_FLOAT,
    // TOKEN_TYPE_CHAR,
    // TOKEN_TYPE_TYPE,
    // TOKEN_TYPE_OPERATOR,
    // TOKEN_TYPE_PARENTHESES_BRACKET_OPEN,
    // TOKEN_TYPE_PARENTHESES_BRACKET_CLOSE,
    // TOKEN_TYPE_SOVEREIGN_type,
    // TOKEN_TYPE_SOVEREIGN_main,
    // TOKEN_TYPE_SOVEREIGN_def,
    // TOKEN_TYPE_VARIABLE,
    // TOKEN_TYPE_ACUTED_OPERATOR,
    // TOKEN_TYPE_ACUTED_FUNCTION,
    // TOKEN_TYPE_STRING,
    // TOKEN_TYPE_FUNCTION,
    TREE_TYPE_APPLY,
    TREE_TYPE_INT,
    TREE_TYPE_FLOAT,
    TREE_TYPE_CHAR,
    TREE_TYPE_VARIABLE,
    TREE_TYPE_STRING,
    TREE_TYPE_FUNCTION,
};

#endif // TREE_TYPES__ENUM_H
