
#include "scanner_structs.h"



#ifndef SCANNER_H
#define SCANNER_H

Token* convertToTokens(char* str);

enum {
    FROM_STATE_TYPE,
    FROM_STATE_INT,
    FROM_STATE_FLOAT,
    FROM_STATE_WORD,
    FROM_STATE_PARENTHESES_BRACKET_OPEN,
    FROM_STATE_PARENTHESES_BRACKET_CLOSE,
    FROM_STATE_OPERATOR,
    FROM_STATE_START,
    FROM_STATE_END,
    FROM_STATE_UNDEF,
    FROM_STATE_STRING,
    FROM_STATE_ACUTED_FUNCTION,
    FROM_STATE_ACUTED_OPERATOR,
};

#endif // SCANNER_H
