#ifndef TOKEN_TYPES__ENUM_H
#define TOKEN_TYPES__ENUM_H

enum TOKEN_TYPE__ENUM {
    TOKEN_TYPE_UNDEF,
    TOKEN_TYPE_INT,
    TOKEN_TYPE_FLOAT,
    TOKEN_TYPE_CHAR,
    TOKEN_TYPE_TYPE,
    TOKEN_TYPE_OPERATOR,
    TOKEN_TYPE_PARENTHESES_BRACKET_OPEN,
    TOKEN_TYPE_PARENTHESES_BRACKET_CLOSE,
    TOKEN_TYPE_SOVEREIGN_type,
    TOKEN_TYPE_SOVEREIGN_main,
    TOKEN_TYPE_SOVEREIGN_def,
    TOKEN_TYPE_VARIABLE,
    TOKEN_TYPE_ACUTED_OPERATOR,
    TOKEN_TYPE_ACUTED_FUNCTION,
    TOKEN_TYPE_STRING,
    TOKEN_TYPE_FUNCTION,
};

#endif //TOKEN_TYPES__ENUM_H
