





enum COMMANDS {
    COMMAND_END_OF_DATA = 0x00,
    COMMAND_BLANK_01,
    COMMAND_BLANK_02,
    COMMAND_BLANK_03,
    COMMAND_BLANK_04,
    COMMAND_BLANK_05,
    COMMAND_NEED_FOR_ADDRESS,
    COMMAND_DATA_ADDRESS,
    COMMAND_PUSHARG,
    COMMAND_LENIN,
    COMMAND_PUSH,
    COMMAND_CALL,
    COMMAND_RET,
    COMMAND_END,

    COMMAND_STANDARD_ADD,
    COMMAND_STANDARD_SUB,
    COMMAND_STANDARD_MUL,
    COMMAND_STANDARD_DIV,
    COMMAND_STANDARD_PRINT_INT,
};
